### ISSUE TITLE
Running on EC2 crashes on this line. 

### ISSUE THREAD

**Issue by umbernhard** [votingworks/arlo-cvr-encryption#50]
https://github.com/votingworks/arlo-cvr-encryption/blob/dd9553409ac750714f3d411a53b318d2a7d9737b/src/arlo_e2e/root_qrcode.py#L112

```
Traceback (most recent call last):
  File "/home/ubuntu/arlo_tally_ballots.py", line 89, in <module>
    rtally = ray_tally_everything(
  File "/home/ubuntu/src/arlo-e2e/src/arlo_e2e/ray_tally.py", line 411, in ray_tally_everything
    gen_root_qrcode(
  File "/home/ubuntu/src/arlo-e2e/src/arlo_e2e/root_qrcode.py", line 112, in gen_root_qrcode
    if qr_data[k].startswith("http"):
AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by danwallach** [comment]
I believe this is fixed and can be closed.
```
        qr_value = str(qr_data[k])  # because sometimes it's not a string
```
